(()=>{'use strict';
if(window.NovaDepthV2)return;
const app=document.getElementById('appShell');if(!app)return;
const K={m:'nova.metrics',d:'nova.details',h:'nova.history',g:'nova.goals',r:'nova.reminders.v2',sl:'nova.sleep.session.v2',tm:'nova.sport.timer.v2'};
const DM={sport:{current:2,max:3},food:{current:3,max:8},water:{current:4,max:8},sleep:{current:1,max:8}},DD={sport:{steps:7432,calories:320,minutes:42},water:{ml:1500},food:{kcal:1540,protein:120,fat:56,carbs:180},sleep:{minutes:448,quality:91,mode:false}},DG={steps:10000,water:2000,kcal:2000,sleep:480};
const R0={water:{enabled:true,time:'10:00',label:'Выпить воды'},food:{enabled:false,time:'13:00',label:'Питание'},sport:{enabled:false,time:'18:30',label:'Тренировка'},sleep:{enabled:true,time:'22:30',label:'Подготовиться ко сну'}};
const O=['sport','food','water','sleep'],L={sport:'Спорт',food:'Питание',water:'Вода',sleep:'Сон'};
const EX=[['Разминка','Разминка','5–10 минут'],['Ходьба','Ходьба','Свободный темп'],['Подъём прямой ноги','ЛФК','Контроль движения'],['Сгибание и разгибание','ЛФК','Мягкая амплитуда'],['Ягодичный мост','ЛФК','Укрепление'],['Растяжка','Растяжка','Спокойный темп']];
let kind='sport',screen=null,modal=null,x0=0,y0=0,tick=0,remTick=0;
const cp=v=>JSON.parse(JSON.stringify(v)),cl=(v,a,b)=>Math.min(b,Math.max(a,Number(v)||0)),rd=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??cp(f)}catch(_){return cp(f)}},wr=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
const id=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,dk=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,fmt=n=>new Intl.NumberFormat('ru-RU').format(Math.round(Number(n)||0)),tm=i=>new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date(i)),dur=n=>{n=Math.max(0,Math.round(Number(n)||0));return`${Math.floor(n/60)} ч ${String(n%60).padStart(2,'0')} мин`},esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function S(){return{m:rd(K.m,DM),d:rd(K.d,DD),h:rd(K.h,[]),g:{...DG,...rd(K.g,{})}}}function save(s){wr(K.m,s.m);wr(K.d,s.d);wr(K.h,s.h.slice(0,500));document.querySelectorAll('.metric[data-kind]').forEach(e=>{let q=s.m[e.dataset.kind];if(!q)return;e.querySelector('strong').textContent=`${q.current} / ${q.max}`;e.querySelector('.metric-track i').style.width=`${Math.round(q.current/q.max*100)}%`});window.NovaBalance?.update?.();window.NovaIntelligence?.update?.()}
function rec(s,t,v,l,z={}){s.h.unshift({id:id(),type:t,value:Number(v)||0,label:l,at:new Date().toISOString(),...z})}function today(h,t){return h.filter(e=>e.type===t&&dk(new Date(e.at))===dk())}function toast(t){let e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1700)}
function ico(k){return k==='water'?'<svg viewBox="0 0 64 64"><path d="M32 5C26 18 16 29 16 42a16 16 0 0 0 32 0C48 29 38 18 32 5Z"/></svg>':k==='sleep'?'<svg viewBox="0 0 64 64"><path d="M48 47A23 23 0 0 1 22 12a22 22 0 1 0 26 35Z"/></svg>':k==='food'?'<svg viewBox="0 0 64 64"><path d="M54 10C32 12 15 24 11 40c-3 13 7 20 18 18 20-3 30-23 25-48Z"/><path d="M17 52C29 43 39 31 49 17" fill="none" stroke="white" stroke-opacity=".65" stroke-width="3"/></svg>':'<svg viewBox="0 0 64 64"><circle cx="44" cy="10" r="6"/><path d="M35 20 25 30l-8-3-4 8 13 5 7-6 4 7-8 8-9 10 7 5 12-12 6-5 5 5 5 11 8-3-6-15-11-10-7-12 4-4 7 4 4-8-10-6c-4-2-7-1-9 2Z"/></svg>'}
function ensure(){if(screen)return screen;screen=document.createElement('section');screen.className='depth-v2';screen.hidden=true;screen.innerHTML=`<header class="dv2-top"><button class="dv2-round" data-v2-close>‹</button><div class="dv2-brand"><img src="./icons/nova-icon-192.png"><span><strong>Nova+</strong><small>Глубина</small></span></div><button class="dv2-round" data-v2-rem>⌁</button></header><nav class="dv2-tabs">${O.map(k=>`<button data-v2-tab="${k}">${L[k]}</button>`).join('')}</nav><main class="dv2-view"></main>`;document.body.appendChild(screen);screen.addEventListener('touchstart',e=>{let t=e.changedTouches[0];x0=t.clientX;y0=t.clientY},{passive:true});screen.addEventListener('touchend',e=>{let t=e.changedTouches[0],dx=t.clientX-x0,dy=t.clientY-y0;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.3){let i=O.indexOf(kind);if(dx<0&&i<3)set(O[i+1]);if(dx>0&&i>0)set(O[i-1])}},{passive:true});return screen}
function open(k='sport'){kind=O.includes(k)?k:'sport';ensure().hidden=false;document.documentElement.classList.add('dv2-open');render()}function close(){if(screen)screen.hidden=true;document.documentElement.classList.remove('dv2-open');clearInterval(tick)}function set(k){kind=k;render()}
function hero(k,a,b){return`<section class="dv2-hero dv2-${k}"><div class="dv2-visual">${ico(k)}</div><div class="dv2-hero-copy"><small>${L[k]}</small><strong>${a}</strong><span>${b}</span></div></section>`}function list(a,k){if(!a.length)return'<div class="dv2-empty">Пока нет записей</div>';return`<div class="dv2-history">${a.map(e=>`<article>${e.photo?`<span class="dv2-photo"><img src="${e.photo}"></span>`:`<span class="dv2-history-icon">${ico(k)}</span>`}<span><strong>${esc(e.label||L[k])}</strong><small>${k==='sleep'?new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(e.at)):tm(e.at)}${k==='food'&&e.protein!=null?` · Б ${fmt(e.protein)} · Ж ${fmt(e.fat)} · У ${fmt(e.carbs)}`:''}</small></span><b>${k==='water'?`+${fmt(e.value)} мл`:k==='food'?`${fmt(e.value)} ккал`:k==='sleep'?dur(e.value):`${fmt(e.value)} мин`}</b></article>`).join('')}</div>`}
function render(){let s=S(),v=ensure().querySelector('.dv2-view');screen.querySelectorAll('[data-v2-tab]').forEach(b=>b.classList.toggle('active',b.dataset.v2Tab===kind));v.innerHTML=kind==='water'?water(s):kind==='food'?food(s):kind==='sleep'?sleep(s):sport(s);if(kind==='sport')timerTicker()}
function water(s){let a=today(s.h,'water');return`${hero('water',`${fmt(s.d.water.ml)} мл`,`из ${fmt(s.g.water)} мл`)}<section class="dv2-card"><div class="dv2-card-head"><div><small>Быстро</small><h2>Добавить воду</h2></div><button data-v2-water-undo ${a.length?'':'disabled'}>Отменить последнее</button></div><div class="dv2-water-quick">${[250,350,500,750].map(x=>`<button data-v2-water="${x}">+${x} мл</button>`).join('')}</div></section><section class="dv2-card"><div class="dv2-card-head"><div><small>Сегодня</small><h2>История стаканов</h2></div><b>${a.length}</b></div>${list(a,'water')}</section>`}
function food(s){let a=today(s.h,'food');return`${hero('food',`${fmt(s.d.food.kcal)} ккал`,`из ${fmt(s.g.kcal)} ккал`)}<section class="dv2-macros"><article><small>Б</small><strong>${fmt(s.d.food.protein)} г</strong></article><article><small>Ж</small><strong>${fmt(s.d.food.fat)} г</strong></article><article><small>У</small><strong>${fmt(s.d.food.carbs)} г</strong></article></section><section class="dv2-card"><div class="dv2-actions-grid"><button class="dv2-primary" data-v2-food-camera>⌾ Сфотографировать еду</button><button data-v2-food-add>＋ Добавить вручную</button></div></section><section class="dv2-card"><div class="dv2-card-head"><div><small>Сегодня</small><h2>Дневник питания</h2></div><b>${a.length}</b></div>${list(a,'food')}</section>`}
function TS(){return{running:false,start:0,elapsed:0,...rd(K.tm,{})}}function TMS(t=TS()){return Number(t.elapsed||0)+(t.running&&t.start?Date.now()-t.start:0)}function TT(t=TS()){let n=Math.floor(TMS(t)/1000),h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=n%60;return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function sport(s){let a=today(s.h,'sport'),t=TS();return`${hero('sport',`${fmt(s.d.sport.minutes)} мин`,`${fmt(s.d.sport.steps)} шагов · ${fmt(s.d.sport.calories)} ккал`)}<section class="dv2-card dv2-timer-card"><div><small>Таймер тренировки</small><strong data-v2-time>${TT(t)}</strong></div><div class="dv2-timer-actions"><button class="dv2-primary" data-v2-timer>${t.running?'Пауза':t.elapsed?'Продолжить':'Старт'}</button><button data-v2-timer-end ${TMS(t)<1000?'disabled':''}>Завершить</button></div></section><section class="dv2-card"><div class="dv2-card-head"><div><small>Библиотека</small><h2>Упражнения и ЛФК</h2></div></div><div class="dv2-exercises">${EX.map((x,i)=>`<button data-v2-ex="${i}"><span>${x[1]}</span><strong>${x[0]}</strong><small>${x[2]}</small></button>`).join('')}</div></section><section class="dv2-card"><div class="dv2-card-head"><div><small>Сегодня</small><h2>История тренировок</h2></div><b>${a.length}</b></div>${list(a,'sport')}</section>`}
function sleep(s){let a=s.h.filter(e=>e.type==='sleep').slice(0,12),q=rd(K.sl,null),run=!!q?.at,mins=run?(Date.now()-new Date(q.at))/60000:0;return`${hero('sleep',dur(s.d.sleep.minutes),`качество ${fmt(s.d.sleep.quality)}%`)}<section class="dv2-card dv2-sleep-now"><div><small>${run?'Сон идёт':'Сегодня'}</small><h2>${run?`Начат в ${tm(q.at)}`:'Режим сна'}</h2>${run?`<strong>${dur(mins)}</strong>`:'<p>Запусти сон перед тем, как лечь. Nova+ сохранит длительность после остановки.</p>'}</div><button class="dv2-primary" data-v2-sleep>${run?'Завершить сон':'Начать сон'}</button></section><section class="dv2-card"><div class="dv2-card-head"><div><small>Последние записи</small><h2>История ночей</h2></div><button data-v2-sleep-add>Добавить</button></div>${list(a,'sleep')}</section>`}
function M(h){if(!modal){modal=document.createElement('div');modal.className='dv2-modal-wrap';document.body.appendChild(modal)}modal.innerHTML=`<div class="dv2-modal-backdrop" data-v2-mclose></div><section class="dv2-modal">${h}</section>`;modal.hidden=false;document.documentElement.classList.add('dv2-modal-open')}function MC(){if(modal)modal.hidden=true;document.documentElement.classList.remove('dv2-modal-open')}function MH(t,s=''){return`<header><div><small>${s}</small><h2>${t}</h2></div><button data-v2-mclose>×</button></header>`}
function foodForm(camera=false){M(`${MH('Добавить еду','Дневник питания')}<form data-v2-food-form><label><span>Фото</span><input type="file" name="photo" accept="image/*" capture="environment"></label><label><span>Название</span><input name="name" placeholder="Например, обед" required></label><div class="dv2-form-grid"><label><span>Калории</span><input name="kcal" type="number" min="0" required></label><label><span>Белки, г</span><input name="protein" type="number" min="0" step=".1"></label><label><span>Жиры, г</span><input name="fat" type="number" min="0" step=".1"></label><label><span>Углеводы, г</span><input name="carbs" type="number" min="0" step=".1"></label></div><button class="dv2-primary dv2-full">Сохранить</button></form>`);if(camera)setTimeout(()=>modal.querySelector('input[type=file]')?.click(),80)}function exForm(i){let x=EX[i];M(`${MH(x[0],x[1])}<form data-v2-ex-form><input type="hidden" name="name" value="${esc(x[0])}"><label><span>Длительность, мин</span><input name="minutes" type="number" min="1" value="10" required></label><label><span>Калории</span><input name="calories" type="number" min="0" value="0"></label><button class="dv2-primary dv2-full">Записать</button></form>`)}function sleepForm(){M(`${MH('Добавить сон','История ночей')}<form data-v2-sleep-form><div class="dv2-form-grid"><label><span>Часы</span><input name="hours" type="number" min="0" max="18" value="7"></label><label><span>Минуты</span><input name="minutes" type="number" min="0" max="59" value="30"></label></div><label><span>Качество, %</span><input name="quality" type="number" min="1" max="100" value="85"></label><button class="dv2-primary dv2-full">Сохранить</button></form>`)}
function rem(){let r={...R0,...rd(K.r,{})};M(`${MH('Напоминания','Расписание Nova+')}<div class="dv2-reminders">${O.map(k=>{let x={...R0[k],...(r[k]||{})};return`<label class="dv2-reminder-row"><span><strong>${L[k]}</strong><small>${x.label}</small></span><input type="time" data-rtime="${k}" value="${x.time}"><input type="checkbox" data-ren="${k}" ${x.enabled?'checked':''}></label>`}).join('')}</div><button class="dv2-primary dv2-full" data-rsave>Сохранить расписание</button><button class="dv2-link dv2-full" data-rnotify>Разрешить уведомления</button><p class="dv2-note">Расписание работает в приложении; фоновая доставка зависит от поддержки PWA на устройстве.</p>`)}
function addW(v){let s=S();v=cl(v,1,3000);s.d.water.ml+=v;s.m.water.current=cl(Math.round(s.d.water.ml/250),0,s.m.water.max);rec(s,'water',v,'Вода');save(s);toast(`+${v} мл воды`);render()}function undoW(){let s=S(),i=s.h.findIndex(e=>e.type==='water'&&dk(new Date(e.at))===dk());if(i<0)return;let e=s.h.splice(i,1)[0];s.d.water.ml=cl(s.d.water.ml-e.value,0,99999);s.m.water.current=cl(Math.round(s.d.water.ml/250),0,s.m.water.max);save(s);toast('Последний стакан отменён');render()}
async function photo(file){if(!file||!file.size)return'';return new Promise(res=>{let r=new FileReader;r.onload=()=>{let im=new Image;im.onload=()=>{let c=document.createElement('canvas'),m=720,sc=Math.min(1,m/Math.max(im.width,im.height));c.width=Math.round(im.width*sc);c.height=Math.round(im.height*sc);c.getContext('2d').drawImage(im,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.72))};im.src=r.result};r.onerror=()=>res('');r.readAsDataURL(file)})}
async function addF(d,f){let s=S(),p=await photo(f),k=cl(d.kcal,0,10000),P=cl(d.protein,0,9999),F=cl(d.fat,0,9999),C=cl(d.carbs,0,9999);s.d.food.kcal+=k;s.d.food.protein+=P;s.d.food.fat+=F;s.d.food.carbs+=C;s.m.food.current=cl(s.m.food.current+1,0,s.m.food.max);rec(s,'food',k,d.name||'Приём пищи',{protein:P,fat:F,carbs:C,photo:p});save(s);MC();toast('Еда добавлена');render()}function addSp(d){let s=S(),m=cl(d.minutes,1,600),cal=cl(d.calories,0,99999);s.d.sport.minutes+=m;s.d.sport.calories+=cal;s.m.sport.current=cl(s.m.sport.current+1,0,s.m.sport.max);rec(s,'sport',m,d.name||'Тренировка',{calories:cal});save(s);MC();toast('Тренировка сохранена');render()}function addSl(m,q=85){let s=S();m=cl(m,1,1080);q=cl(q,1,100);s.d.sleep.minutes=m;s.d.sleep.quality=q;s.m.sleep.current=cl(Math.round(m/60),0,s.m.sleep.max);rec(s,'sleep',m,'Сон',{quality:q});save(s);MC();toast('Сон сохранён');render()}
function togSl(){let q=rd(K.sl,null);if(q?.at){localStorage.removeItem(K.sl);addSl(Math.max(1,Math.round((Date.now()-new Date(q.at))/60000)),85)}else{wr(K.sl,{at:new Date().toISOString()});toast('Сон начат');render()}}function togT(){let t=TS();if(t.running){t.elapsed=TMS(t);t.running=false;t.start=0}else{t.running=true;t.start=Date.now()}wr(K.tm,t);render()}function endT(){let m=TMS();if(m<1000)return;localStorage.removeItem(K.tm);addSp({name:'Тренировка по таймеру',minutes:Math.max(1,Math.round(m/60000)),calories:0})}function timerTicker(){clearInterval(tick);tick=setInterval(()=>{let e=screen?.querySelector('[data-v2-time]');if(e)e.textContent=TT();let b=screen?.querySelector('[data-v2-timer-end]');if(b)b.disabled=TMS()<1000},250)}
function saveR(){let r={...R0,...rd(K.r,{})};O.forEach(k=>r[k]={...R0[k],...(r[k]||{}),enabled:!!modal.querySelector(`[data-ren="${k}"]`)?.checked,time:modal.querySelector(`[data-rtime="${k}"]`)?.value||R0[k].time});wr(K.r,r);MC();toast('Расписание сохранено');sched()}async function notify(){if(!('Notification'in window))return toast('Уведомления не поддерживаются');let p=await Notification.requestPermission();toast(p==='granted'?'Уведомления разрешены':'Разрешение не получено')}function sched(){clearInterval(remTick);remTick=setInterval(checkR,30000);checkR()}function checkR(){let r={...R0,...rd(K.r,{})},n=new Date(),t=`${String(n.getHours()).padStart(2,'0')}:${String(n.getMinutes()).padStart(2,'0')}`,d=dk();O.forEach(k=>{let x={...R0[k],...(r[k]||{})},f=`nova.rf.${k}`;if(x.enabled&&x.time===t&&localStorage.getItem(f)!==d){localStorage.setItem(f,d);if('Notification'in window&&Notification.permission==='granted')new Notification(`Nova+ · ${L[k]}`,{body:x.label,icon:'./icons/nova-icon-192.png'});else toast(x.label)}})}
document.addEventListener('click',e=>{let m=e.target.closest('.metric[data-kind]');if(m&&O.includes(m.dataset.kind)){e.preventDefault();e.stopImmediatePropagation();return open(m.dataset.kind)}if(!screen||screen.hidden)return;if(e.target.closest('[data-v2-close]'))return close();let b=e.target.closest('[data-v2-tab]');if(b)return set(b.dataset.v2Tab);if(e.target.closest('[data-v2-rem]'))return rem();let w=e.target.closest('[data-v2-water]');if(w)return addW(w.dataset.v2Water);if(e.target.closest('[data-v2-water-undo]'))return undoW();if(e.target.closest('[data-v2-food-camera]'))return foodForm(true);if(e.target.closest('[data-v2-food-add]'))return foodForm();if(e.target.closest('[data-v2-timer]'))return togT();if(e.target.closest('[data-v2-timer-end]'))return endT();let ex=e.target.closest('[data-v2-ex]');if(ex)return exForm(+ex.dataset.v2Ex);if(e.target.closest('[data-v2-sleep]'))return togSl();if(e.target.closest('[data-v2-sleep-add]'))return sleepForm();if(e.target.closest('[data-v2-mclose]'))return MC();if(e.target.closest('[data-rsave]'))return saveR();if(e.target.closest('[data-rnotify]'))return notify()},true);
document.addEventListener('submit',async e=>{let f=e.target;if(!(f instanceof HTMLFormElement))return;if(f.matches('[data-v2-food-form]')){e.preventDefault();let d=new FormData(f);await addF(Object.fromEntries(d.entries()),d.get('photo'))}if(f.matches('[data-v2-ex-form]')){e.preventDefault();addSp(Object.fromEntries(new FormData(f).entries()))}if(f.matches('[data-v2-sleep-form]')){e.preventDefault();let d=Object.fromEntries(new FormData(f).entries());addSl(Number(d.hours||0)*60+Number(d.minutes||0),d.quality)}},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(modal&&!modal.hidden)MC();else close()}});sched();
window.NovaDepthV2={open,close,openFoodCamera:()=>{open('food');setTimeout(()=>foodForm(true),80)},quickWater:()=>open('water'),openTimer:()=>open('sport'),openReminders:rem,refresh:render};
})();