(() => {
  "use strict";
  const TF_URL = "https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.11.0/dist/tf.min.js";
  const MOBILENET_URL = "https://cdn.jsdelivr.net/npm/@tensorflow-models/mobilenet@2.1.0/dist/mobilenet.min.js";
  const STORAGE_KEY = "vector-health-v1";
  let model = null;
  let modelPromise = null;
  let stream = null;
  let breathingTimer = null;
  let audioContext = null;
  let currentNoise = null;
  const foodDatabase = {
    banana:{name:"Банан",kcal:89,protein:1.1,fat:.3,carbs:23,emoji:"🍌"}, apple:{name:"Яблоко",kcal:52,protein:.3,fat:.2,carbs:14,emoji:"🍎"}, orange:{name:"Апельсин",kcal:47,protein:.9,fat:.1,carbs:12,emoji:"🍊"}, pizza:{name:"Пицца",kcal:266,protein:11,fat:10,carbs:33,emoji:"🍕"}, hamburger:{name:"Бургер",kcal:295,protein:17,fat:14,carbs:24,emoji:"🍔"}, cheeseburger:{name:"Чизбургер",kcal:303,protein:16,fat:14,carbs:30,emoji:"🍔"}, "french fries":{name:"Картофель фри",kcal:312,protein:3.4,fat:15,carbs:41,emoji:"🍟"}, hotdog:{name:"Хот-дог",kcal:290,protein:10,fat:17,carbs:24,emoji:"🌭"}, sandwich:{name:"Сэндвич",kcal:250,protein:12,fat:9,carbs:30,emoji:"🥪"}, burrito:{name:"Буррито",kcal:206,protein:8,fat:7,carbs:28,emoji:"🌯"}, salad:{name:"Салат",kcal:35,protein:2,fat:1,carbs:5,emoji:"🥗"}, soup:{name:"Суп",kcal:55,protein:3,fat:2,carbs:7,emoji:"🍲"}, spaghetti:{name:"Спагетти",kcal:158,protein:5.8,fat:.9,carbs:31,emoji:"🍝"}, rice:{name:"Рис",kcal:130,protein:2.7,fat:.3,carbs:28,emoji:"🍚"}, bread:{name:"Хлеб",kcal:265,protein:9,fat:3.2,carbs:49,emoji:"🍞"}, croissant:{name:"Круассан",kcal:406,protein:8,fat:21,carbs:46,emoji:"🥐"}, bagel:{name:"Бейгл",kcal:250,protein:10,fat:1.5,carbs:49,emoji:"🥯"}, pancake:{name:"Блинчики",kcal:227,protein:6,fat:10,carbs:28,emoji:"🥞"}, waffle:{name:"Вафли",kcal:291,protein:8,fat:14,carbs:33,emoji:"🧇"}, cheese:{name:"Сыр",kcal:350,protein:25,fat:27,carbs:2,emoji:"🧀"}, meat:{name:"Мясо",kcal:200,protein:26,fat:10,carbs:0,emoji:"🍖"}, chicken:{name:"Курица",kcal:165,protein:31,fat:3.6,carbs:0,emoji:"🍗"}, hen:{name:"Курица",kcal:165,protein:31,fat:3.6,carbs:0,emoji:"🍗"}, fish:{name:"Рыба",kcal:180,protein:22,fat:9,carbs:0,emoji:"🐟"}, salmon:{name:"Лосось",kcal:208,protein:20,fat:13,carbs:0,emoji:"🐟"}, shrimp:{name:"Креветки",kcal:99,protein:24,fat:.3,carbs:.2,emoji:"🦐"}, egg:{name:"Яйцо",kcal:155,protein:13,fat:11,carbs:1.1,emoji:"🥚"}, milk:{name:"Молоко",kcal:52,protein:2.8,fat:2.5,carbs:4.7,emoji:"🥛"}, coffee:{name:"Кофе без добавок",kcal:2,protein:.1,fat:0,carbs:0,emoji:"☕"}, espresso:{name:"Кофе без добавок",kcal:2,protein:.1,fat:0,carbs:0,emoji:"☕"}, cake:{name:"Торт",kcal:371,protein:5,fat:15,carbs:55,emoji:"🍰"}, cookie:{name:"Печенье",kcal:488,protein:6,fat:24,carbs:64,emoji:"🍪"}, chocolate:{name:"Шоколад",kcal:546,protein:5,fat:31,carbs:61,emoji:"🍫"}, candy:{name:"Конфеты",kcal:394,protein:2,fat:8,carbs:80,emoji:"🍬"}, "ice cream":{name:"Мороженое",kcal:207,protein:3.5,fat:11,carbs:24,emoji:"🍨"}, doughnut:{name:"Пончик",kcal:452,protein:5,fat:25,carbs:51,emoji:"🍩"}
  };
  function injectMarkup(){
    if(document.getElementById("hp-ai-modal"))return;
    const layer=document.createElement("div"); layer.className="hp-time-glow"; layer.setAttribute("aria-hidden","true"); document.body.prepend(layer);
    const actions=document.createElement("div"); actions.className="hp-actions"; actions.innerHTML=`<button class="hp-fab hp-ai-fab" id="hp-ai-open" type="button" aria-label="Открыть ИИ-диетолога"><span>🤖</span><b>ИИ-диетолог</b></button><button class="hp-fab hp-sos-fab" id="hp-sos-open" type="button" aria-label="Открыть дыхательную помощь"><span>🆘</span><b>SOS</b></button><button class="hp-sound" id="hp-sound-toggle" type="button" aria-label="Включить спокойный фоновый звук">🔇</button>`; document.body.appendChild(actions);
    const aiModal=document.createElement("div"); aiModal.id="hp-ai-modal"; aiModal.className="hp-modal"; aiModal.setAttribute("aria-hidden","true"); aiModal.innerHTML=`<div class="hp-modal-card hp-ai-card" role="dialog" aria-modal="true" aria-labelledby="hp-ai-title"><header class="hp-modal-head"><div><span class="hp-kicker">HEALTH+ · PHOTO AI</span><h2 id="hp-ai-title">🤖 ИИ-диетолог</h2><p>Сфотографируйте блюдо или выберите фото.</p></div><button class="hp-close" id="hp-ai-close" type="button" aria-label="Закрыть">×</button></header><div class="hp-camera-box"><video id="hp-camera" autoplay playsinline muted></video><img id="hp-preview" alt="Выбранное фото еды" /><div id="hp-camera-placeholder" class="hp-camera-placeholder"><span>📸</span><small>Камера выключена</small></div><div id="hp-scan" class="hp-scan">🔍 Анализ изображения…</div></div><div class="hp-button-row"><button class="hp-primary" id="hp-camera-toggle" type="button">📷 Включить камеру</button><button class="hp-secondary" id="hp-capture" type="button" disabled>🔍 Распознать</button><label class="hp-secondary hp-upload" for="hp-file">📁 Выбрать фото</label><input id="hp-file" type="file" accept="image/*" capture="environment" hidden /></div><div id="hp-model-status" class="hp-status">ИИ-модель загрузится при первом использовании.</div><div id="hp-results" class="hp-results"></div><p class="hp-disclaimer">Распознавание и калорийность по фото приблизительные. Размер порции, рецепт и способ приготовления камера точно не определяет.</p></div>`; document.body.appendChild(aiModal);
    const sosModal=document.createElement("div"); sosModal.id="hp-sos-modal"; sosModal.className="hp-modal"; sosModal.setAttribute("aria-hidden","true"); sosModal.innerHTML=`<div class="hp-modal-card hp-sos-card" role="dialog" aria-modal="true" aria-labelledby="hp-sos-title"><button class="hp-close" id="hp-sos-close" type="button" aria-label="Закрыть">×</button><span class="hp-kicker">СПОКОЙНЫЙ РИТМ</span><h2 id="hp-sos-title">Дыхательное упражнение</h2><div class="hp-breathe-wrap"><div class="hp-breathe-circle" id="hp-breathe-circle"></div></div><strong class="hp-breathe-text" id="hp-breathe-text">Вдох · 4 сек</strong><p>Дышите без усилия. Если кружится голова — остановитесь и вернитесь к обычному дыханию.</p><button class="hp-primary hp-full" id="hp-sos-done" type="button">Закрыть упражнение</button><small class="hp-emergency">При реальной угрозе здоровью используйте местный номер экстренной помощи.</small></div>`; document.body.appendChild(sosModal);
  }
  function setTimeGlow(){const h=new Date().getHours(),l=document.querySelector(".hp-time-glow");if(l)l.dataset.period=h>=6&&h<12?"morning":h>=12&&h<18?"day":h>=18&&h<22?"evening":"night"}
  function openModal(id){const m=document.getElementById(id);if(!m)return;m.classList.add("open");m.setAttribute("aria-hidden","false");document.documentElement.classList.add("hp-modal-open")}
  function closeModal(id){const m=document.getElementById(id);if(!m)return;m.classList.remove("open");m.setAttribute("aria-hidden","true");if(!document.querySelector(".hp-modal.open"))document.documentElement.classList.remove("hp-modal-open")}
  function loadScript(src,readyCheck){if(readyCheck())return Promise.resolve();return new Promise((resolve,reject)=>{const existing=[...document.scripts].find(s=>s.src===src);if(existing){existing.addEventListener("load",resolve,{once:true});existing.addEventListener("error",reject,{once:true});return}const script=document.createElement("script");script.src=src;script.async=true;script.crossOrigin="anonymous";script.onload=resolve;script.onerror=reject;document.head.appendChild(script)})}
  async function ensureModel(){if(model)return model;if(modelPromise)return modelPromise;const status=document.getElementById("hp-model-status");modelPromise=(async()=>{try{status.innerHTML='<span class="hp-spinner"></span> Загружаю TensorFlow и MobileNet…';await loadScript(TF_URL,()=>Boolean(window.tf));await loadScript(MOBILENET_URL,()=>Boolean(window.mobilenet));status.innerHTML='<span class="hp-spinner"></span> Загружаю ИИ-модель…';model=await window.mobilenet.load();status.textContent="✅ ИИ-модель готова";return model}catch(error){console.error("Health+ model load error",error);status.textContent="❌ Модель не загрузилась. Для первого запуска нужен интернет.";modelPromise=null;throw error}})();return modelPromise}
  async function toggleCamera(){const video=document.getElementById("hp-camera"),preview=document.getElementById("hp-preview"),placeholder=document.getElementById("hp-camera-placeholder"),toggle=document.getElementById("hp-camera-toggle"),capture=document.getElementById("hp-capture");if(stream){stopCamera();return}try{await ensureModel();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:960}},audio:false});video.srcObject=stream;video.style.display="block";preview.style.display="none";placeholder.style.display="none";toggle.textContent="📷 Выключить камеру";capture.disabled=false}catch(error){console.error("Health+ camera error",error);document.getElementById("hp-model-status").textContent="Не удалось открыть камеру. Можно выбрать фото из галереи."}}
  function stopCamera(){if(stream)stream.getTracks().forEach(track=>track.stop());stream=null;const video=document.getElementById("hp-camera"),toggle=document.getElementById("hp-camera-toggle"),capture=document.getElementById("hp-capture"),placeholder=document.getElementById("hp-camera-placeholder"),preview=document.getElementById("hp-preview");if(video){video.srcObject=null;video.style.display="none"}if(toggle)toggle.textContent="📷 Включить камеру";if(capture)capture.disabled=true;if(placeholder&&preview.style.display!=="block")placeholder.style.display="flex"}
  async function analyze(element){const scan=document.getElementById("hp-scan"),results=document.getElementById("hp-results");scan.classList.add("show");results.innerHTML="";try{const net=await ensureModel(),predictions=await net.classify(element,12),matches=[];for(const prediction of predictions){const label=prediction.className.toLowerCase();for(const key of Object.keys(foodDatabase)){if((label.includes(key)||key.includes(label))&&!matches.some(m=>m.key===key))matches.push({key,probability:prediction.probability,source:prediction.className})}}matches.sort((a,b)=>b.probability-a.probability);matches.length?renderFoodMatches(matches.slice(0,3)):renderGeneric(predictions.slice(0,3))}catch(error){console.error("Health+ classify error",error);results.innerHTML='<div class="hp-empty">❌ Не удалось проанализировать изображение.</div>'}finally{scan.classList.remove("show")}}
  function renderFoodMatches(matches){const results=document.getElementById("hp-results");const cards=matches.map((match,index)=>{const food=foodDatabase[match.key],confidence=Math.round(match.probability*100);return `<article class="hp-food-card"><div class="hp-food-main"><span class="hp-food-emoji">${food.emoji}</span><div><strong>${food.name}</strong><small>≈ ${food.kcal} ккал / 100 г</small></div><b>${confidence}%</b></div><div class="hp-confidence"><i style="width:${confidence}%"></i></div><div class="hp-macros">Б ${food.protein} · Ж ${food.fat} · У ${food.carbs}</div>${index===0?`<button class="hp-add-diary" type="button" data-hp-add="${match.key}">+ Добавить 100 г в дневник VECTOR</button>`:""}</article>`}).join("");results.innerHTML=`<div class="hp-result-head"><strong>Похоже на:</strong><span>калорийность ориентировочная</span></div>${cards}`}
  function renderGeneric(predictions){const results=document.getElementById("hp-results"),rows=predictions.map(p=>`<div class="hp-generic-row"><span>${escapeHtml(p.className)}</span><b>${Math.round(p.probability*100)}%</b></div>`).join("");results.innerHTML=`<div class="hp-empty"><strong>Еду уверенно определить не удалось.</strong><p>Попробуйте снять блюдо крупнее и при хорошем освещении.</p>${rows}</div>`}
  function addToVectorDiary(key){const food=foodDatabase[key];if(!food)return;try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");saved.foodLogs=saved.foodLogs||{};const now=new Date(),day=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`;const entry={id:`hp-${Date.now()}`,name:`${food.name} · распознано по фото`,meal:"snack",grams:100,kcal:food.kcal,protein:food.protein,fat:food.fat,carbs:food.carbs};saved.foodLogs[day]=[...(saved.foodLogs[day]||[]),entry];localStorage.setItem(STORAGE_KEY,JSON.stringify(saved));const button=document.querySelector(`[data-hp-add="${CSS.escape(key)}"]`);if(button){button.textContent="✅ Добавлено. Обновляю дневник…";button.disabled=true}setTimeout(()=>location.reload(),500)}catch(error){console.error("Health+ diary write error",error);document.getElementById("hp-model-status").textContent="Не удалось добавить запись в дневник."}}
  async function handleFile(file){if(!file)return;const preview=document.getElementById("hp-preview"),video=document.getElementById("hp-camera"),placeholder=document.getElementById("hp-camera-placeholder");stopCamera();const url=URL.createObjectURL(file);preview.onload=async()=>{URL.revokeObjectURL(url);preview.style.display="block";video.style.display="none";placeholder.style.display="none";await analyze(preview)};preview.onerror=()=>{URL.revokeObjectURL(url);document.getElementById("hp-model-status").textContent="Не удалось открыть изображение."};preview.src=url}
  function startBreathing(){stopBreathing();const circle=document.getElementById("hp-breathe-circle"),text=document.getElementById("hp-breathe-text");let inhale=true;const applyPhase=()=>{circle.classList.toggle("inhale",inhale);circle.classList.toggle("exhale",!inhale);text.textContent=inhale?"Вдох · 4 сек":"Выдох · 6 сек";const duration=inhale?4000:6000;breathingTimer=setTimeout(()=>{inhale=!inhale;applyPhase()},duration)};applyPhase()}
  function stopBreathing(){clearTimeout(breathingTimer);breathingTimer=null}
  async function toggleSound(){const button=document.getElementById("hp-sound-toggle");if(currentNoise){try{currentNoise.source.stop()}catch{}currentNoise=null;button.textContent="🔇";return}try{const AudioCtx=window.AudioContext||window.webkitAudioContext;audioContext=audioContext||new AudioCtx();await audioContext.resume();const length=audioContext.sampleRate*2,buffer=audioContext.createBuffer(1,length,audioContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=Math.random()*2-1;const source=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),gain=audioContext.createGain();source.buffer=buffer;source.loop=true;filter.type="lowpass";filter.frequency.value=650;gain.gain.value=.025;source.connect(filter).connect(gain).connect(audioContext.destination);source.start();currentNoise={source,gain};button.textContent="🔊"}catch(error){console.error("Health+ audio error",error)}}
  function escapeHtml(value){return String(value).replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[ch])}
  function bindEvents(){document.getElementById("hp-ai-open").addEventListener("click",()=>{openModal("hp-ai-modal");ensureModel().catch(()=>{})});document.getElementById("hp-ai-close").addEventListener("click",()=>{stopCamera();closeModal("hp-ai-modal")});document.getElementById("hp-sos-open").addEventListener("click",()=>{openModal("hp-sos-modal");startBreathing()});const closeSos=()=>{stopBreathing();closeModal("hp-sos-modal")};document.getElementById("hp-sos-close").addEventListener("click",closeSos);document.getElementById("hp-sos-done").addEventListener("click",closeSos);document.getElementById("hp-camera-toggle").addEventListener("click",toggleCamera);document.getElementById("hp-capture").addEventListener("click",()=>analyze(document.getElementById("hp-camera")));document.getElementById("hp-file").addEventListener("change",event=>handleFile(event.target.files?.[0]));document.getElementById("hp-results").addEventListener("click",event=>{const button=event.target.closest("[data-hp-add]");if(button)addToVectorDiary(button.dataset.hpAdd)});document.getElementById("hp-sound-toggle").addEventListener("click",toggleSound);for(const id of ["hp-ai-modal","hp-sos-modal"]){document.getElementById(id).addEventListener("click",event=>{if(event.target.id!==id)return;if(id==="hp-ai-modal")stopCamera();if(id==="hp-sos-modal")stopBreathing();closeModal(id)})}document.addEventListener("keydown",event=>{if(event.key!=="Escape")return;if(document.getElementById("hp-ai-modal").classList.contains("open")){stopCamera();closeModal("hp-ai-modal")}if(document.getElementById("hp-sos-modal").classList.contains("open")){stopBreathing();closeModal("hp-sos-modal")}});window.addEventListener("pagehide",()=>{stopCamera();stopBreathing();if(currentNoise){try{currentNoise.source.stop()}catch{}}})}
  function init(){injectMarkup();setTimeGlow();bindEvents();setInterval(setTimeGlow,60000)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
