(()=>{'use strict';
const $=s=>document.querySelector(s),C=$('#irisCanvas'),X=C.getContext('2d'),A=$('#app'),S=$('#stage'),ML=$('#metricLabel'),MV=$('#metricValue'),MC=$('#metricCaption'),MW=$('#modeWhisper'),RM=$('#radialMenu'),RI=[...document.querySelectorAll('.radial-item')],TR=$('#touchRing'),MH=$('#motionHint'),MD=$('#modeDots'),IP=$('#insightPanel'),SP=$('#settingsPanel'),ST=$('#settingsTrigger'),SO=$('#soundToggle'),SS=$('#soundSettings'),SW=$('#soundState');
const M={home:['ГЛАВНАЯ','','КОСНИСЬ ГЛАЗА','IRIS НАБЛЮДАЕТ',[190,214,231],[88,122,145],[214,202,188],110],sport:['СПОРТ','24:17','ТРЕНИРОВКА','ПУЛЬС · ДВИЖЕНИЕ',[224,86,69],[112,39,36],[251,156,118],123.47],water:['ВОДА','1,2 Л','СЕГОДНЯ','БАЛАНС ЖИДКОСТИ',[94,173,230],[34,86,132],[181,224,253],146.83],food:['ПИТАНИЕ','1 420','ККАЛ','ЭНЕРГИЯ ИЗ ЕДЫ',[146,171,112],[65,86,52],[213,169,102],164.81],sleep:['СОН','7 Ч 24 М','ПРОШЛОЙ НОЧЬЮ','ВОССТАНОВЛЕНИЕ',[78,102,155],[31,43,73],[126,146,190],98],insights:['ИТОГИ','84','ИНДЕКС ДНЯ','СВОДКА СОСТОЯНИЯ',[197,211,221],[70,88,103],[190,181,173],130.81]},O=['home','sport','water','food','sleep','insights'];
const rnd=n=>{let q=Math.sin(n*12.9898+78.233)*43758.5453;return q-Math.floor(q)},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),lp=(a,b,t)=>a+(b-a)*t,cc=(a,b,t)=>[lp(a[0],b[0],t),lp(a[1],b[1],t),lp(a[2],b[2],t)],rgba=(c,a=1)=>`rgba(${c[0]|0},${c[1]|0},${c[2]|0},${a})`,ad=(a,b)=>{let d=a-b;while(d>Math.PI)d-=Math.PI*2;while(d<-Math.PI)d+=Math.PI*2;return d};
let mode='home',ac=[...M.home[4]],ic=[...M.home[5]],wc=[...M.home[6]],W=0,H=0,D=1,cx=0,cy=0,R=132,sc=1,ts=1,ys=0,tys=0,ex=0,ey=0,tex=0,tey=0,fib=[],cry=[],flk=[],rip=[],trail=[],flash=0,beat=0,water=0,breath=0,menu=false,sel=null,lastSel=null,mm=0,tmm=0,pupil=0,first=false,hold=0;
let p={id:null,down:false,x:0,y:0,sx:0,sy:0,st:0,a:0,d:0,lx:0,ly:0,lt:0,v:0};

/* iPhone-safe sound: create/resume only inside a real user gesture */
let sound=localStorage.getItem('irisSound')!=='off',unlocked=false,audio=null,timer=0,epoch=0;
function sui(){let locked=sound&&!unlocked;SO?.classList.toggle('locked',locked);SO?.classList.toggle('muted',!sound);SO?.setAttribute('aria-pressed',sound?'true':'false');if(SW)SW.textContent=!sound?'ВЫКЛ':locked?'КОСНИСЬ':'ВКЛ'}
function audioCreate(){if(audio)return audio.c;let AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null,c=new AC(),master=c.createGain(),f=c.createBiquadFilter(),pg=c.createGain(),o1=c.createOscillator(),o2=c.createOscillator(),mg=c.createGain(),mo=c.createOscillator();master.gain.value=.0001;master.connect(c.destination);f.type='lowpass';f.frequency.value=420;f.connect(pg);pg.gain.value=.04;pg.connect(master);o1.type='sine';o2.type='triangle';o1.connect(f);o2.connect(f);o1.start();o2.start();mo.type='sine';mo.frequency.value=220;mg.gain.value=0;mo.connect(mg);mg.connect(master);mo.start();audio={c,master,f,pg,o1,o2,mo,mg};amode(mode);return c}
async function unlock(){if(!sound)return false;let c=audioCreate();if(!c)return false;try{if(c.state!=='running')await c.resume();let b=c.createBuffer(1,1,22050),s=c.createBufferSource(),g=c.createGain();g.gain.value=.00001;s.buffer=b;s.connect(g);g.connect(audio.master);s.start();audio.master.gain.cancelScheduledValues(c.currentTime);audio.master.gain.setValueAtTime(.0001,c.currentTime);audio.master.gain.exponentialRampToValueAtTime(.09,c.currentTime+.22);unlocked=c.state==='running';if(unlocked){world();tone(M[mode][7]*3,.18,.008)}}catch(e){unlocked=false}sui();return unlocked}
function setSound(v){sound=!!v;localStorage.setItem('irisSound',sound?'on':'off');if(!sound){stopWorld();unlocked=false;if(audio){let c=audio.c;audio.master.gain.setTargetAtTime(.0001,c.currentTime,.05);setTimeout(()=>audio?.c.state==='running'&&audio.c.suspend().catch(()=>{}),220)}}sui()}
function amode(m){if(!audio)return;let c=audio.c,r=M[m][7];audio.o1.frequency.setTargetAtTime(r,c.currentTime,.2);audio.o2.frequency.setTargetAtTime(r*1.498,c.currentTime,.2);audio.f.frequency.setTargetAtTime(m==='sleep'?240:m==='sport'?600:m==='water'?680:430,c.currentTime,.2);audio.pg.gain.setTargetAtTime(m==='sleep'?.018:m==='sport'?.035:.04,c.currentTime,.2)}
function tone(fr,d=.2,g=.015,type='sine',slide=1){if(!sound||!unlocked||!audio||audio.c.state!=='running')return;let c=audio.c,o=c.createOscillator(),q=c.createGain();o.type=type;o.frequency.setValueAtTime(fr,c.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,fr*slide),c.currentTime+d);q.gain.setValueAtTime(.0001,c.currentTime);q.gain.exponentialRampToValueAtTime(g,c.currentTime+.012);q.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.connect(q);q.connect(audio.master);o.start();o.stop(c.currentTime+d+.03)}
function thump(){tone(58,.14,.035,'sine',.8);setTimeout(()=>tone(82,.09,.018,'sine',.82),140)}
function waterDrop(){water=1;tone(760+Math.random()*420,.28,.008,'sine',1.35);let e=ec();rip.push({x:e.x+(Math.random()-.5)*R,y:e.y+(Math.random()-.5)*R*.5,l:1,s:1})}
function breathe(){breath=1;tone(72,1.7,.004,'sine',1.01)}
function stopWorld(){epoch++;clearTimeout(timer)}
function world(){stopWorld();if(!sound||!unlocked||document.hidden)return;amode(mode);let e=epoch;const loop=()=>{if(e!==epoch||!sound||!unlocked||document.hidden)return;let d=4400;if(mode==='sport'){beat=1;thump();d=780}else if(mode==='water'){waterDrop();d=1600+Math.random()*900}else if(mode==='sleep'){breathe();d=4300}else if(mode==='food'){tone(M.food[7]*2,.75,.007);setTimeout(()=>tone(M.food[7]*2.5,.6,.004),160);d=3200}else if(mode==='insights'){tone(M.insights[7]*5,.65,.006);d=3900}else{tone(M.home[7]*2,.8,.004);d=5200}timer=setTimeout(loop,d)};timer=setTimeout(loop,mode==='sport'?180:700)}
function moveAudio(x,y,v){if(!unlocked||!audio)return;let c=audio.c,e=ec(),nx=cl((x-e.x)/(R*sc),-1,1),ny=cl((y-e.y)/(R*sc),-1,1);audio.mo.frequency.setTargetAtTime(170+(ny+1)*100,c.currentTime,.03);audio.mg.gain.setTargetAtTime(.001+cl(v/1.2,0,1)*(mode==='sleep'?.005:.012),c.currentTime,.03)}
function stopMove(){if(audio)audio.mg.gain.setTargetAtTime(0,audio.c.currentTime,.05)}
function fxTap(){tone(M[mode][7]*4,.15,.014,'sine',1.12)}function fxHold(){tone(M[mode][7],.46,.022,'sine',1.28)}function fxSwipe(d){tone(M[mode][7]*2.1,.2,.012,'sine',d>0?1.2:.84)}function fxMode(){tone(M[mode][7]*2,.35,.01);world()}
sui();

function ec(){return{x:cx+ex,y:cy+ys+ey}}
function build(){fib=[];cry=[];flk=[];let n=cl(Math.floor(R*3.7),430,650);for(let k=0;k<n;k++)fib.push({a:k/n*Math.PI*2+(rnd(k)-.5)*.075,ri:.22+rnd(k*3.7)*.16,rm:.48+rnd(k*7.1)*.18,ro:.73+rnd(k*8.1)*.25,w:.16+rnd(k*5.4)*.72,al:.035+rnd(k*7.2)*.18,b:(rnd(k*9.4)-.5)*.20,h:rnd(k*11.1)>.88,s:rnd(k*13.5)});for(let k=0;k<68;k++)cry.push({a:k/68*Math.PI*2+rnd(k*9.3)*.14,r:.38+rnd(k*2.1)*.37,l:.035+rnd(k*4.8)*.08,w:.6+rnd(k*5.7)*1.8,al:.10+rnd(k*8.4)*.22});for(let k=0;k<120;k++)flk.push({a:rnd(k*2.2)*Math.PI*2,r:.29+rnd(k*3.9)*.58,s:.3+rnd(k*4.7)*1.2,al:.025+rnd(k*8.8)*.12,h:rnd(k*5.1)>.78})}
function layout(){let rr=R*(mode==='insights'?.66:1),yy=cy+(mode==='insights'?-H*.1:0);MW.style.top=Math.max(90,yy-rr-28)+'px';$('#metric').style.top=Math.min(H-150,yy+rr+25)+'px';document.documentElement.style.setProperty('--eye-x',cx+'px');document.documentElement.style.setProperty('--eye-y',yy+'px');document.documentElement.style.setProperty('--eye-r',rr+'px')}
function resize(){D=Math.min(2,devicePixelRatio||1);W=innerWidth|0;H=innerHeight|0;C.width=W*D;C.height=H*D;C.style.width=W+'px';C.style.height=H+'px';X.setTransform(D,0,0,D,0,0);cx=W/2;cy=H*.44;R=Math.min(W*.36,H*.19,184);build();layout();posMenu()}
function posMenu(){let e=ec(),z=R*sc*2.48;RM.style.left=e.x+'px';RM.style.top=e.y+'px';RM.style.width=z+'px';RM.style.height=z+'px'}
function inside(x,y,m=1.07){let e=ec();return Math.hypot(x-e.x,y-e.y)<=R*sc*m}
function palette(){let m=M[mode];ac=cc(ac,m[4],.028);ic=cc(ic,m[5],.028);wc=cc(wc,m[6],.028);document.documentElement.style.setProperty('--accent',`${ac[0]|0} ${ac[1]|0} ${ac[2]|0}`)}
function dots(){MD.innerHTML='';O.forEach(m=>{let s=document.createElement('span');if(m===mode)s.className='active';MD.appendChild(s)});MD.classList.toggle('visible',mode!=='home')}
function ui(){let m=M[mode];ML.textContent=m[0];MV.textContent=m[1];MC.textContent=m[2];MW.textContent=m[3];A.className=`app mode-${mode}${menu?' menu-open':''}${SP.classList.contains('open')?' settings-open':''}`;IP.classList.toggle('visible',mode==='insights');ts=mode==='insights'?.66:1;tys=mode==='insights'?-H*.1:0;dots();layout();posMenu()}
function hint(){if(first)return;first=true;MH.classList.add('hidden')}
function setMode(m,fx=true){if(!M[m])return;mode=m;pupil=1;flash=1;ui();hint();amode(m);fx?fxMode():world();try{navigator.vibrate?.(8)}catch{}}
function pulse(x,y){TR.style.left=x+'px';TR.style.top=y+'px';TR.classList.remove('pulse');void TR.offsetWidth;TR.classList.add('pulse');rip.push({x,y,l:1});pupil=1;fxTap()}
function openMenu(){if(menu||!p.down)return;menu=true;sel=null;lastSel=null;tmm=1;RM.classList.add('open');A.classList.add('menu-open');posMenu();hint();fxHold();try{navigator.vibrate?.(12)}catch{}}
function closeMenu(commit=true){if(!menu)return;let s=sel;menu=false;sel=lastSel=null;tmm=0;RI.forEach(i=>i.classList.remove('active'));RM.classList.remove('open');A.classList.remove('menu-open');if(commit&&s)setMode(s)}
function choose(x,y){if(!menu)return;let e=ec(),dx=x-e.x,dy=y-e.y,d=Math.hypot(dx,dy);if(d<R*.42)sel=null;else{let a=Math.atan2(dy,dx);sel=a>-.25*Math.PI&&a<=.25*Math.PI?'food':a>.25*Math.PI&&a<=.75*Math.PI?'sleep':a<=-.25*Math.PI&&a>-.75*Math.PI?'sport':'water'}RI.forEach(i=>i.classList.toggle('active',i.dataset.mode===sel));if(sel&&sel!==lastSel){lastSel=sel;tone(M[mode][7]*5,.07,.008);try{navigator.vibrate?.(4)}catch{}}}
function openSettings(){closeMenu(false);SP.classList.add('open');A.classList.add('settings-open');hint()}function closeSettings(){SP.classList.remove('open');A.classList.remove('settings-open')}

function down(e){if(e.target.closest('button'))return;let x=e.clientX,y=e.clientY;if(!inside(x,y,1.1))return;p.id=e.pointerId;p.down=true;p.x=p.sx=p.lx=x;p.y=p.sy=p.ly=y;p.st=p.lt=performance.now();let q=ec(),dx=x-q.x,dy=y-q.y;p.a=Math.atan2(dy,dx);p.d=Math.hypot(dx,dy);try{S.setPointerCapture(e.pointerId)}catch{}clearTimeout(hold);hold=setTimeout(openMenu,540);tex=cl(dx/W*25,-12,12);tey=cl(dy/H*25,-10,10);trail=[{x,y,l:1}];moveAudio(x,y,0)}
function move(e){if(!p.down||e.pointerId!==p.id)return;let x=e.clientX,y=e.clientY,n=performance.now(),dt=Math.max(1,n-p.lt),step=Math.hypot(x-p.lx,y-p.ly);p.v=step/dt;p.lt=n;p.lx=x;p.ly=y;p.x=x;p.y=y;let q=ec(),dx=x-q.x,dy=y-q.y;p.a=Math.atan2(dy,dx);p.d=Math.hypot(dx,dy);if(Math.hypot(x-p.sx,y-p.sy)>15&&!menu)clearTimeout(hold);tex=cl(dx/W*27,-14,14);tey=cl(dy/H*27,-12,12);trail.push({x,y,l:1});if(trail.length>14)trail.shift();moveAudio(x,y,p.v);if(menu)choose(x,y)}
function finish(e,cancel=false){if(!p.down||e.pointerId!==p.id)return;clearTimeout(hold);stopMove();let x=e.clientX,y=e.clientY,dt=performance.now()-p.st,dx=x-p.sx,dy=y-p.sy,d=Math.hypot(dx,dy);p.down=false;tex=tey=0;try{S.releasePointerCapture(e.pointerId)}catch{}p.id=null;if(cancel){closeMenu(false);return}if(menu){closeMenu(true);return}if(dt<390&&d<24){pulse(x,y);hint();if(mode==='home'){MC.textContent='УДЕРЖИВАЙ ДЛЯ МЕНЮ';setTimeout(()=>mode==='home'&&(MC.textContent=M.home[2]),1000)}return}if(Math.abs(dx)>66&&Math.abs(dx)>Math.abs(dy)*1.16){let i=O.indexOf(mode);fxSwipe(dx<0?1:-1);setMode(dx<0?O[(i+1)%O.length]:O[(i-1+O.length)%O.length],false);return}if(dy<-84&&Math.abs(dy)>Math.abs(dx)*1.08){fxSwipe(1);setMode('insights',false);return}if(dy>84&&Math.abs(dy)>Math.abs(dx)*1.08)openSettings()}

function bg(e,r){X.clearRect(0,0,W,H);let g=X.createRadialGradient(e.x,e.y,r*.15,e.x,e.y,r*2.5);g.addColorStop(0,rgba(ac,.045));g.addColorStop(.36,rgba(ac,.014));g.addColorStop(1,'rgba(0,0,0,0)');X.fillStyle=g;X.fillRect(0,0,W,H);rip=rip.filter(q=>q.l>.018);X.save();X.globalCompositeOperation='screen';for(let q of rip){let rr=(1-q.l)*(q.s?115:190);X.beginPath();X.arc(q.x,q.y,rr,0,Math.PI*2);X.strokeStyle=rgba(ac,q.l*(q.s?.055:.07));X.lineWidth=q.s?.7:1;X.stroke();q.l*=q.s?.94:.95}X.restore()}
function motion(){X.save();X.globalCompositeOperation='screen';for(let k=1;k<trail.length;k++){let a=trail[k-1],b=trail[k];X.beginPath();X.moveTo(a.x,a.y);X.lineTo(b.x,b.y);X.strokeStyle=rgba(ac,b.l*.05);X.lineWidth=.5+b.l;X.stroke();a.l*=.87;b.l*=.9}X.restore()}
function modefx(t,e,r){if(mode==='sport'){X.save();X.beginPath();X.arc(e.x,e.y,r*(1.07+beat*.012),-Math.PI*.72,-Math.PI*.72+Math.PI*2*.74);X.strokeStyle=rgba(ac,.68+beat*.2);X.lineWidth=1.2+beat*.6;X.shadowBlur=8+beat*7;X.shadowColor=rgba(ac,.35);X.stroke();X.restore();beat*=.9}else if(mode==='water'){X.save();X.globalCompositeOperation='screen';X.beginPath();for(let k=0;k<=36;k++){let x=e.x-r*.9+r*1.8*k/36,y=e.y+r*.72+Math.sin(k/36*Math.PI*2+t*.0022)*r*(.015+water*.02);k?X.lineTo(x,y):X.moveTo(x,y)}X.strokeStyle=rgba(wc,.08+water*.08);X.lineWidth=.8;X.stroke();X.restore();water*=.94}else if(mode==='sleep'){breath*=.994}}
function spokes(e,r){if(mm<.01)return;let q=1-Math.pow(1-mm,3),len=r*(.6+.55*q);X.save();X.globalCompositeOperation='screen';for(let k=0;k<4;k++){let a=-Math.PI/2+k*Math.PI/2;X.beginPath();X.moveTo(e.x+Math.cos(a)*r*.28,e.y+Math.sin(a)*r*.28);X.lineTo(e.x+Math.cos(a)*len,e.y+Math.sin(a)*len);X.strokeStyle=rgba(ac,.03+.08*q);X.lineWidth=.6;X.stroke()}X.restore()}
function draw(t){palette();sc=lp(sc,ts,.055);ys=lp(ys,tys,.055);ex=lp(ex,tex,.08);ey=lp(ey,tey,.08);mm=lp(mm,tmm,.12);pupil=lp(pupil,0,.055);flash=lp(flash,0,.07);let e=ec(),r=R*sc*(1+Math.sin(t*.00072)*.007+beat*.008);posMenu();bg(e,r);modefx(t,e,r);motion();X.save();X.translate(e.x,e.y);
for(let k=0;k<2;k++){X.beginPath();X.arc(0,0,r*(1.035+k*.035),0,Math.PI*2);X.strokeStyle=rgba(ac,.025-k*.007);X.lineWidth=.55;X.stroke()}
let base=X.createRadialGradient(-r*.08,-r*.11,r*.05,0,0,r*1.02);base.addColorStop(0,'#000');base.addColorStop(.16,rgba(ic,.88));base.addColorStop(.37,rgba(ac,.37));base.addColorStop(.68,rgba(ic,.31));base.addColorStop(.91,'rgba(12,18,22,.76)');base.addColorStop(1,'rgba(0,0,0,.96)');X.beginPath();X.arc(0,0,r,0,Math.PI*2);X.fillStyle=base;X.fill();X.save();X.beginPath();X.arc(0,0,r*.985,0,Math.PI*2);X.clip();X.globalCompositeOperation='screen';
for(let f of fib){let a=f.a+Math.sin(t*.00075+f.s*12)*.005,inf=p.down?Math.exp(-Math.pow(ad(a,p.a),2)/.13)*cl(1.16-p.d/(r*1.22),0,1):0,r1=r*(f.ri-inf*.01),rm=r*f.rm,r2=r*(f.ro+inf*.022),a2=a+f.b,am=a+f.b*.42;X.beginPath();X.moveTo(Math.cos(a)*r1,Math.sin(a)*r1);X.quadraticCurveTo(Math.cos(am)*rm,Math.sin(am)*rm,Math.cos(a2)*r2,Math.sin(a2)*r2);X.strokeStyle=f.h?rgba(wc,f.al*.56*(1+inf*.9)):rgba(ac,f.al*(1+inf*.8));X.lineWidth=f.w+inf*.3;X.stroke()}
X.globalCompositeOperation='source-over';for(let c of cry){let rr=r*c.r;X.beginPath();X.arc(Math.cos(c.a)*rr,Math.sin(c.a)*rr,r*c.l,c.a-.55,c.a+.55);X.strokeStyle=`rgba(0,0,0,${c.al})`;X.lineWidth=c.w;X.stroke()}X.globalCompositeOperation='screen';for(let f of flk){X.beginPath();X.arc(Math.cos(f.a)*r*f.r,Math.sin(f.a)*r*f.r,f.s,0,Math.PI*2);X.fillStyle=f.h?rgba(wc,f.al*.6):rgba(ac,f.al);X.fill()}let sh=X.createLinearGradient(-r*.8,-r*.7,r*.7,r*.7);sh.addColorStop(0,'rgba(255,255,255,.09)');sh.addColorStop(.25,'rgba(255,255,255,.015)');sh.addColorStop(.7,rgba(ac,.04));sh.addColorStop(1,'rgba(255,255,255,0)');X.fillStyle=sh;X.beginPath();X.arc(0,0,r*.98,0,Math.PI*2);X.fill();X.restore();
let rim=X.createRadialGradient(0,0,r*.8,0,0,r*1.055);rim.addColorStop(0,'rgba(0,0,0,0)');rim.addColorStop(.75,rgba(ac,.025));rim.addColorStop(.88,'rgba(2,5,7,.55)');rim.addColorStop(1,'rgba(0,0,0,.995)');X.beginPath();X.arc(0,0,r*1.055,0,Math.PI*2);X.fillStyle=rim;X.fill();let pr=r*(.195+mm*.085+pupil*.021+Math.sin(t*.00048)*.004);X.beginPath();X.arc(0,0,pr,0,Math.PI*2);X.fillStyle='#000';X.fill();X.beginPath();X.arc(0,0,pr*1.04,0,Math.PI*2);X.strokeStyle=rgba(ac,.12);X.lineWidth=.65;X.stroke();X.save();X.globalCompositeOperation='screen';let hx=-r*.25,hy=-r*.31,hg=X.createRadialGradient(hx,hy,0,hx,hy,r*.14);hg.addColorStop(0,'rgba(255,255,255,.28)');hg.addColorStop(.16,'rgba(255,255,255,.1)');hg.addColorStop(1,'rgba(255,255,255,0)');X.fillStyle=hg;X.beginPath();X.arc(hx,hy,r*.14,0,Math.PI*2);X.fill();X.restore();if(mode==='sleep'){let z=.30+breath*.05;X.fillStyle='rgba(0,0,0,.994)';X.beginPath();X.ellipse(0,-r*(1-z),r*1.32,r*.76,0,0,Math.PI*2);X.fill();X.beginPath();X.ellipse(0,r*(1-z),r*1.32,r*.76,0,0,Math.PI*2);X.fill()}X.restore();spokes(e,r);requestAnimationFrame(draw)}

RI.forEach(i=>i.addEventListener('click',e=>{e.stopPropagation();sel=i.dataset.mode;closeMenu(true)}));ST.addEventListener('click',()=>{unlock();openSettings()});document.querySelectorAll('[data-close-settings]').forEach(el=>el.addEventListener('click',closeSettings));async function toggle(e){e?.stopPropagation();if(!sound){setSound(true);await unlock()}else if(!unlocked)await unlock();else setSound(false)}SO?.addEventListener('click',toggle);SS?.addEventListener('click',toggle);window.addEventListener('pointerdown',()=>{if(sound&&(!unlocked||audio?.c.state!=='running'))unlock()},{capture:true,passive:true});S.addEventListener('pointerdown',down);S.addEventListener('pointermove',move);S.addEventListener('pointerup',e=>finish(e));S.addEventListener('pointercancel',e=>finish(e,true));addEventListener('resize',resize,{passive:true});document.addEventListener('visibilitychange',async()=>{if(document.hidden){clearTimeout(hold);p.down=false;closeMenu(false);stopMove();stopWorld();return}if(sound&&audio){try{await audio.c.resume();unlocked=audio.c.state==='running';if(unlocked)world()}catch{unlocked=false}sui()}});resize();ui();sui();requestAnimationFrame(draw);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=iris09').catch(()=>{}));})();
