(()=>{'use strict';
const $=s=>document.querySelector(s),C=$('#irisCanvas'),X=C.getContext('2d'),A=$('#app'),S=$('#stage'),ML=$('#metricLabel'),MV=$('#metricValue'),MC=$('#metricCaption'),MW=$('#modeWhisper'),RM=$('#radialMenu'),RI=[...document.querySelectorAll('.radial-item')],TR=$('#touchRing'),MH=$('#motionHint'),MD=$('#modeDots'),IP=$('#insightPanel'),SP=$('#settingsPanel'),ST=$('#settingsTrigger'),SO=$('#soundToggle'),SS=$('#soundSettings'),SW=$('#soundState');
const M={home:['ГЛАВНАЯ','','КОСНИСЬ ГЛАЗА','IRIS НАБЛЮДАЕТ',[188,211,229],[73,108,135],55],sport:['СПОРТ','24:17','ТРЕНИРОВКА','ПУЛЬС · ДВИЖЕНИЕ',[214,78,65],[95,33,31],61.7],water:['ВОДА','','ДНЕВНОЙ БАЛАНС','ЖИДКОСТЬ · БАЛАНС',[80,162,224],[27,78,126],73.4],food:['ПИТАНИЕ','1 420','ККАЛ','ЭНЕРГИЯ ИЗ ЕДЫ',[137,160,102],[54,75,43],82.4],sleep:['СОН','7 Ч 24 М','ПРОШЛОЙ НОЧЬЮ','ВОССТАНОВЛЕНИЕ',[68,91,145],[26,37,66],49],insights:['ИТОГИ','84','ИНДЕКС ДНЯ','СВОДКА СОСТОЯНИЯ',[187,202,214],[62,80,96],65.4]},O=['home','sport','water','food','sleep','insights'];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,rnd=n=>{let q=Math.sin(n*12.9898+78.233)*43758.5453;return q-Math.floor(q)},rgba=(c,a=1)=>`rgba(${c[0]|0},${c[1]|0},${c[2]|0},${a})`;
let mode='home',W=0,H=0,D=1,cx=0,cy=0,R=135,eyeX=0,eyeY=0,targetX=0,targetY=0,scale=1,targetScale=1,yShift=0,targetShift=0,fib=[],dots=[],rip=[],menu=false,sel=null,hold=0,mm=0,tmm=0,pupil=0;
let p={id:null,down:false,sx:0,sy:0,x:0,y:0,st:0,lx:0,ly:0,lt:0,v:0,a:0,d:0};
let waterMl=clamp(parseInt(localStorage.getItem('irisWaterMl')||'1250',10)||1250,0,5000),waterGoal=clamp(parseInt(localStorage.getItem('irisWaterGoalMl')||'2000',10)||2000,500,5000),wave=0;
const fmt=ml=>(ml/1000).toFixed(2).replace('.',',').replace(/,00$/,',0')+' Л';

const style=document.createElement('style');style.textContent=`
:root{--eye-r:140px}.mode-whisper{font-size:7px!important;letter-spacing:.42em!important;color:rgba(241,246,250,.30)!important}.metric-label{font-size:8px!important;letter-spacing:.4em!important}.metric-caption{font-size:7px!important}.radial-menu{width:calc(var(--eye-r)*2.65)!important;height:calc(var(--eye-r)*2.65)!important}.radial-item{min-width:82px!important;height:32px!important;font-size:7px!important;background:rgba(2,4,7,.78)!important;border-color:rgba(255,255,255,.06)!important}.water-panel{position:absolute;z-index:8;left:50%;bottom:calc(max(18px,env(safe-area-inset-bottom)) + 68px);width:min(82vw,330px);transform:translateX(-50%) translateY(12px);opacity:0;pointer-events:none;transition:.35s cubic-bezier(.16,1,.3,1)}.app.mode-water .water-panel{opacity:1;transform:translateX(-50%);pointer-events:auto}.water-line{height:1px;background:rgba(255,255,255,.07);overflow:hidden}.water-line span{display:block;height:100%;background:rgba(var(--accent),.72);box-shadow:0 0 12px rgba(var(--accent),.32);transition:width .4s ease}.water-head{display:flex;justify-content:space-between;align-items:baseline;margin-top:12px}.water-head strong{font-size:20px;font-weight:250}.water-head small{font-size:8px;letter-spacing:.18em;color:rgba(255,255,255,.34)}.water-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:13px}.water-actions button{height:40px;border-radius:22px;border:1px solid rgba(255,255,255,.07);background:rgba(255,255,255,.022);font-size:10px;letter-spacing:.12em;color:rgba(255,255,255,.68)}.water-hint{text-align:center;margin-top:10px;font-size:7px;letter-spacing:.22em;color:rgba(255,255,255,.2)}.app.mode-water #motionHint{opacity:0}.sound-trigger{width:auto!important;padding:0 10px!important;gap:7px!important}.sound-trigger:after{content:'ЗВУК';font-size:7px;letter-spacing:.18em;color:rgba(255,255,255,.25)}@media(max-height:720px){.water-panel{bottom:calc(max(18px,env(safe-area-inset-bottom)) + 46px)}}`;
document.head.appendChild(style);
const wp=document.createElement('section');wp.className='water-panel';wp.innerHTML='<div class="water-line"><span></span></div><div class="water-head"><strong></strong><small></small></div><div class="water-actions"><button data-water="-250">− 250</button><button data-water="250">+ 250</button></div><div class="water-hint">СВАЙП ВВЕРХ · +250 МЛ</div>';S.appendChild(wp);const wbar=wp.querySelector('.water-line span'),wcur=wp.querySelector('strong'),wgoal=wp.querySelector('small');
function waterUI(){let pr=clamp(waterMl/waterGoal,0,1);wbar.style.width=pr*100+'%';wcur.textContent=fmt(waterMl);wgoal.textContent='ИЗ '+fmt(waterGoal);if(mode==='water'){MV.textContent=fmt(waterMl);MC.textContent=`ИЗ ${fmt(waterGoal)} · ${Math.round(pr*100)}%`}}

let sound=localStorage.getItem('irisSound')!=='off',unlocked=false,audio=null,worldT=0,epoch=0;
function soundUI(){let locked=sound&&!unlocked;SO?.classList.toggle('locked',locked);SO?.classList.toggle('muted',!sound);SO?.setAttribute('aria-pressed',sound?'true':'false');if(SW)SW.textContent=!sound?'ВЫКЛ':locked?'КОСНИСЬ':'ВКЛ'}
function makeAudio(){if(audio)return audio.c;let AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null,c=new AC(),master=c.createGain(),f=c.createBiquadFilter(),g=c.createGain(),o1=c.createOscillator(),o2=c.createOscillator(),o3=c.createOscillator(),move=c.createOscillator(),mg=c.createGain();master.gain.value=.0001;master.connect(c.destination);f.type='lowpass';f.frequency.value=210;f.connect(g);g.gain.value=.05;g.connect(master);[o1,o2,o3].forEach(o=>o.connect(f));o1.type='sine';o2.type='triangle';o3.type='sine';o1.detune.value=-8;o2.detune.value=5;o3.detune.value=11;o1.start();o2.start();o3.start();move.type='sine';move.frequency.value=160;mg.gain.value=0;move.connect(mg);mg.connect(master);move.start();audio={c,master,f,g,o1,o2,o3,move,mg};audioMode();return c}
async function unlock(){if(!sound)return false;let c=makeAudio();if(!c)return false;try{if(c.state!=='running')await c.resume();let o=c.createOscillator(),g=c.createGain();g.gain.value=.000001;o.connect(g);g.connect(audio.master);o.start();o.stop(c.currentTime+.02);unlocked=c.state==='running';if(unlocked){audio.master.gain.cancelScheduledValues(c.currentTime);audio.master.gain.setValueAtTime(.0001,c.currentTime);audio.master.gain.exponentialRampToValueAtTime(.095,c.currentTime+.3);world();tone(M[mode][6]*4,.22,.006)}}catch{unlocked=false}soundUI();return unlocked}
function tone(fr,d=.2,g=.012,type='sine',slide=1){if(!sound||!unlocked||!audio||audio.c.state!=='running')return;let c=audio.c,o=c.createOscillator(),v=c.createGain();o.type=type;o.frequency.setValueAtTime(fr,c.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,fr*slide),c.currentTime+d);v.gain.setValueAtTime(.0001,c.currentTime);v.gain.exponentialRampToValueAtTime(g,c.currentTime+.015);v.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.connect(v);v.connect(audio.master);o.start();o.stop(c.currentTime+d+.03)}
function audioMode(){if(!audio)return;let c=audio.c,r=M[mode][6];audio.o1.frequency.setTargetAtTime(r,c.currentTime,.4);audio.o2.frequency.setTargetAtTime(r*1.498,c.currentTime,.4);audio.o3.frequency.setTargetAtTime(r*.5,c.currentTime,.4);audio.f.frequency.setTargetAtTime(mode==='sleep'?145:mode==='sport'?285:mode==='water'?250:205,c.currentTime,.3);audio.g.gain.setTargetAtTime(mode==='sleep'?.026:.05,c.currentTime,.3)}
function stopWorld(){epoch++;clearTimeout(worldT)}function world(){stopWorld();if(!sound||!unlocked||document.hidden)return;audioMode();let e=epoch;const loop=()=>{if(e!==epoch||!sound||!unlocked||document.hidden)return;let d=6000;if(mode==='sport'){tone(42,.48,.014,'sine',.78);setTimeout(()=>tone(64,.28,.006,'sine',.82),190);d=780}else if(mode==='water'){tone(260+Math.random()*120,.7,.004,'sine',.94+Math.random()*.14);d=2600+Math.random()*1200}else if(mode==='sleep'){tone(34,2.5,.003,'sine',1.01);d=5800}else if(mode==='food'){tone(96,.9,.004,'triangle',.94);d=4500}else if(mode==='insights'){tone(392,.8,.004);setTimeout(()=>tone(523,.6,.003),180);d=5300}else{tone(42,.7,.006,'sine',.84);d=7200}worldT=setTimeout(loop,d)};worldT=setTimeout(loop,mode==='sport'?200:900)}
function setSound(v){sound=!!v;localStorage.setItem('irisSound',sound?'on':'off');if(!sound){stopWorld();unlocked=false;if(audio){let c=audio.c;audio.master.gain.setTargetAtTime(.0001,c.currentTime,.06);setTimeout(()=>audio?.c.state==='running'&&audio.c.suspend().catch(()=>{}),260)}}soundUI()}
function moveAudio(x,y,v){if(!unlocked||!audio)return;let c=audio.c,e=ec(),ny=clamp((y-e.y)/(R*scale),-1,1);audio.move.frequency.setTargetAtTime(115+(ny+1)*95,c.currentTime,.03);audio.mg.gain.setTargetAtTime(.001+clamp(v/1.1,0,1)*(mode==='sleep'?.003:.01),c.currentTime,.03)}
function waterSfx(add){tone(add?480:280,.3,.009,'sine',add?1.45:.72);setTimeout(()=>tone(add?820:420,.2,.004,'sine',add?1.1:.8),70)}
soundUI();

function ec(){return{x:cx+eyeX,y:cy+yShift+eyeY}}
function build(){fib=[];dots=[];let n=clamp(Math.floor(R*3.7),420,620);for(let i=0;i<n;i++)fib.push({a:i/n*Math.PI*2+(rnd(i)-.5)*.085,ri:.23+rnd(i*3.2)*.14,ro:.70+rnd(i*7.7)*.25,b:(rnd(i*9.1)-.5)*.18,w:.14+rnd(i*4.4)*.62,al:.03+rnd(i*6.7)*.16,s:rnd(i*11.3)});for(let i=0;i<120;i++)dots.push({a:rnd(i*2.3)*Math.PI*2,r:.31+rnd(i*3.1)*.56,s:.25+rnd(i*4.8),al:.02+rnd(i*7.9)*.1})}
function resize(){D=Math.min(2,devicePixelRatio||1);W=innerWidth|0;H=innerHeight|0;C.width=W*D;C.height=H*D;C.style.width=W+'px';C.style.height=H+'px';X.setTransform(D,0,0,D,0,0);cx=W/2;cy=H*.435;R=Math.min(W*.34,H*.178,174);build();layout()}
function layout(){let rr=R*(mode==='insights'?.66:1),yy=cy+(mode==='insights'?-H*.1:0);document.documentElement.style.setProperty('--eye-x',cx+'px');document.documentElement.style.setProperty('--eye-y',yy+'px');document.documentElement.style.setProperty('--eye-r',rr+'px');MW.style.top=Math.max(88,yy-rr-34)+'px';$('#metric').style.top=Math.min(H-180,yy+rr+(mode==='water'?17:31))+'px'}
function inside(x,y,m=1.08){let e=ec();return Math.hypot(x-e.x,y-e.y)<=R*scale*m}
function ui(){let m=M[mode];ML.textContent=m[0];MV.textContent=m[1];MC.textContent=m[2];MW.textContent=m[3];A.className=`app mode-${mode}${menu?' menu-open':''}${SP.classList.contains('open')?' settings-open':''}`;IP.classList.toggle('visible',mode==='insights');targetScale=mode==='insights'?.66:1;targetShift=mode==='insights'?-H*.1:0;MD.innerHTML='';O.forEach(v=>{let d=document.createElement('span');if(v===mode)d.className='active';MD.appendChild(d)});MD.classList.toggle('visible',mode!=='home'&&mode!=='water');layout();waterUI();audioMode()}
function setMode(m){if(!M[m])return;mode=m;pupil=1;ui();world();if(unlocked)tone(M[m][6]*2,.3,.007);try{navigator.vibrate?.(8)}catch{}}
function pulse(x,y){TR.style.left=x+'px';TR.style.top=y+'px';TR.classList.remove('pulse');void TR.offsetWidth;TR.classList.add('pulse');rip.push({x,y,l:1});pupil=1;if(unlocked)tone(M[mode][6]*4,.16,.01,'sine',1.1)}
function openMenu(){if(menu||!p.down)return;menu=true;sel=null;tmm=1;RM.classList.add('open');A.classList.add('menu-open');if(unlocked)tone(M[mode][6],.48,.018,'sine',1.28)}function closeMenu(commit=true){if(!menu)return;let s=sel;menu=false;sel=null;tmm=0;RI.forEach(i=>i.classList.remove('active'));RM.classList.remove('open');A.classList.remove('menu-open');if(commit&&s)setMode(s)}
function choose(x,y){let e=ec(),dx=x-e.x,dy=y-e.y,d=Math.hypot(dx,dy);if(d<R*.4)sel=null;else{let a=Math.atan2(dy,dx);sel=a>-.25*Math.PI&&a<=.25*Math.PI?'food':a>.25*Math.PI&&a<=.75*Math.PI?'sleep':a<=-.25*Math.PI&&a>-.75*Math.PI?'sport':'water'}RI.forEach(i=>i.classList.toggle('active',i.dataset.mode===sel))}
function changeWater(d){waterMl=clamp(waterMl+d,0,5000);localStorage.setItem('irisWaterMl',waterMl);wave=1;waterUI();let e=ec();rip.push({x:e.x,y:e.y+R*(.55-waterMl/waterGoal),l:1});if(unlocked)waterSfx(d>0);try{navigator.vibrate?.(d>0?10:6)}catch{}}
function down(e){if(e.target.closest('button'))return;let x=e.clientX,y=e.clientY;if(!inside(x,y,1.1))return;p.id=e.pointerId;p.down=true;p.sx=p.x=p.lx=x;p.sy=p.y=p.ly=y;p.st=p.lt=performance.now();let q=ec(),dx=x-q.x,dy=y-q.y;p.a=Math.atan2(dy,dx);p.d=Math.hypot(dx,dy);try{S.setPointerCapture(e.pointerId)}catch{}clearTimeout(hold);hold=setTimeout(openMenu,560);targetX=clamp(dx/W*24,-11,11);targetY=clamp(dy/H*24,-9,9);moveAudio(x,y,0)}
function move(e){if(!p.down||e.pointerId!==p.id)return;let n=performance.now(),x=e.clientX,y=e.clientY,dt=Math.max(1,n-p.lt);p.v=Math.hypot(x-p.lx,y-p.ly)/dt;p.lt=n;p.lx=x;p.ly=y;p.x=x;p.y=y;let q=ec(),dx=x-q.x,dy=y-q.y;p.a=Math.atan2(dy,dx);p.d=Math.hypot(dx,dy);if(Math.hypot(x-p.sx,y-p.sy)>15&&!menu)clearTimeout(hold);targetX=clamp(dx/W*27,-13,13);targetY=clamp(dy/H*27,-11,11);moveAudio(x,y,p.v);if(menu)choose(x,y)}
function finish(e,cancel=false){if(!p.down||e.pointerId!==p.id)return;clearTimeout(hold);if(audio)audio.mg.gain.setTargetAtTime(0,audio.c.currentTime,.05);let x=e.clientX,y=e.clientY,dt=performance.now()-p.st,dx=x-p.sx,dy=y-p.sy,dist=Math.hypot(dx,dy);p.down=false;targetX=targetY=0;try{S.releasePointerCapture(e.pointerId)}catch{}p.id=null;if(cancel){closeMenu(false);return}if(menu){closeMenu(true);return}if(dt<390&&dist<22){pulse(x,y);return}if(Math.abs(dx)>68&&Math.abs(dx)>Math.abs(dy)*1.15){let i=O.indexOf(mode);setMode(dx<0?O[(i+1)%O.length]:O[(i-1+O.length)%O.length]);return}if(Math.abs(dy)>72&&Math.abs(dy)>Math.abs(dx)*1.08){if(mode==='water'){changeWater(dy<0?250:-250);return}if(dy<0)setMode('insights')}}

function waterFill(t,r){if(mode!=='water')return;let pr=clamp(waterMl/waterGoal,0,1),yy=r*(1-2*pr),amp=r*(.02+.018*wave);X.save();X.beginPath();X.arc(0,0,r*.97,0,Math.PI*2);X.clip();let g=X.createLinearGradient(0,yy-r*.2,0,r);g.addColorStop(0,rgba(M.water[4],.04));g.addColorStop(.3,rgba(M.water[4],.11));g.addColorStop(1,rgba(M.water[5],.28));X.beginPath();X.moveTo(-r,yy);for(let i=0;i<=44;i++){let xx=-r+2*r*i/44,y=yy+Math.sin(i/44*Math.PI*2+t*.0026)*amp;i?X.lineTo(xx,y):X.moveTo(xx,y)}X.lineTo(r,r);X.lineTo(-r,r);X.fillStyle=g;X.fill();X.restore();wave*=.95}
function draw(t){scale=lerp(scale,targetScale,.06);yShift=lerp(yShift,targetShift,.06);eyeX=lerp(eyeX,targetX,.08);eyeY=lerp(eyeY,targetY,.08);mm=lerp(mm,tmm,.11);pupil=lerp(pupil,0,.05);let e=ec(),r=R*scale*(1+Math.sin(t*.00075)*.006),m=M[mode];document.documentElement.style.setProperty('--accent',m[4].join(' '));X.clearRect(0,0,W,H);let bg=X.createRadialGradient(e.x,e.y,0,e.x,e.y,r*2.7);bg.addColorStop(0,rgba(m[4],.045));bg.addColorStop(1,'rgba(0,0,0,0)');X.fillStyle=bg;X.fillRect(0,0,W,H);rip=rip.filter(q=>q.l>.02);for(let q of rip){X.beginPath();X.arc(q.x,q.y,(1-q.l)*150,0,Math.PI*2);X.strokeStyle=rgba(m[4],q.l*.06);X.stroke();q.l*=.95}
X.save();X.translate(e.x,e.y);let base=X.createRadialGradient(0,0,r*.08,0,0,r);base.addColorStop(0,'#000');base.addColorStop(.2,rgba(m[5],.72));base.addColorStop(.45,rgba(m[4],.30));base.addColorStop(.8,rgba(m[5],.22));base.addColorStop(1,'rgba(0,0,0,.2)');X.beginPath();X.arc(0,0,r,0,Math.PI*2);X.fillStyle=base;X.fill();X.save();X.beginPath();X.arc(0,0,r*.985,0,Math.PI*2);X.clip();X.globalCompositeOperation='screen';for(let f of fib){let a=f.a+Math.sin(t*.001+f.s*18)*.006,r1=r*f.ri,r2=r*f.ro,mid=(r1+r2)*.52,ma=a+f.b*.4;X.beginPath();X.moveTo(Math.cos(a)*r1,Math.sin(a)*r1);X.quadraticCurveTo(Math.cos(ma)*mid,Math.sin(ma)*mid,Math.cos(a+f.b)*r2,Math.sin(a+f.b)*r2);X.strokeStyle=rgba(m[4],f.al);X.lineWidth=f.w;X.stroke()}for(let d of dots){X.beginPath();X.arc(Math.cos(d.a)*r*d.r,Math.sin(d.a)*r*d.r,d.s,0,Math.PI*2);X.fillStyle=rgba(m[4],d.al);X.fill()}waterFill(t,r);X.restore();let rim=X.createRadialGradient(0,0,r*.78,0,0,r*1.05);rim.addColorStop(0,'rgba(0,0,0,0)');rim.addColorStop(.88,'rgba(0,0,0,.5)');rim.addColorStop(1,'rgba(0,0,0,.99)');X.beginPath();X.arc(0,0,r*1.05,0,Math.PI*2);X.fillStyle=rim;X.fill();let pr=r*(.205+mm*.08+pupil*.018);X.beginPath();X.arc(0,0,pr,0,Math.PI*2);X.fillStyle='#000';X.fill();X.beginPath();X.arc(0,0,pr*1.02,0,Math.PI*2);X.strokeStyle=rgba(m[4],.12);X.lineWidth=.6;X.stroke();X.save();X.globalCompositeOperation='screen';let hg=X.createRadialGradient(-r*.22,-r*.28,0,-r*.22,-r*.28,r*.12);hg.addColorStop(0,'rgba(255,255,255,.24)');hg.addColorStop(1,'rgba(255,255,255,0)');X.fillStyle=hg;X.beginPath();X.arc(-r*.22,-r*.28,r*.12,0,Math.PI*2);X.fill();X.restore();if(mode==='sleep'){let close=.39+Math.sin(t*.00045)*.01;X.fillStyle='rgba(0,0,0,.99)';X.beginPath();X.ellipse(0,-r*(1.06-close),r*1.35,r*.84,0,0,Math.PI*2);X.fill();X.beginPath();X.ellipse(0,r*(1.06-close),r*1.35,r*.84,0,0,Math.PI*2);X.fill()}X.restore();requestAnimationFrame(draw)}

RI.forEach(i=>i.addEventListener('click',e=>{e.stopPropagation();sel=i.dataset.mode;closeMenu(true)}));wp.querySelectorAll('button').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();changeWater(+b.dataset.water)}));ST.addEventListener('click',()=>{SP.classList.add('open');A.classList.add('settings-open')});document.querySelectorAll('[data-close-settings]').forEach(el=>el.addEventListener('click',()=>{SP.classList.remove('open');A.classList.remove('settings-open')}));SO.addEventListener('click',async e=>{e.stopPropagation();if(!sound){setSound(true);await unlock()}else if(!unlocked)await unlock();else setSound(false)});SS.addEventListener('click',async e=>{e.stopPropagation();if(!sound){setSound(true);await unlock()}else if(!unlocked)await unlock();else setSound(false)});document.addEventListener('pointerdown',()=>{if(sound&&!unlocked)unlock()},{capture:true,passive:true});S.addEventListener('pointerdown',down);S.addEventListener('pointermove',move);S.addEventListener('pointerup',e=>finish(e));S.addEventListener('pointercancel',e=>finish(e,true));addEventListener('resize',resize,{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopWorld();clearTimeout(hold);p.down=false}else if(sound&&audio){audio.c.resume().then(()=>{unlocked=audio.c.state==='running';soundUI();if(unlocked)world()}).catch(()=>{unlocked=false;soundUI()})}});resize();ui();waterUI();requestAnimationFrame(draw);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=iris10').catch(()=>{}));})();
